### ISSUE TITLE
from arcolinux-logout to archlinux-logout

### ISSUE THREAD

**Issue by arcolinuxz** [etrigan63/kittycafe-sm#1]
Could you please change all references of arcolinux-logout into archlinux-logout?
![ArcoLinux-2022-07-01_19-17](https://user-images.githubusercontent.com/36679406/176940909-68fb7c48-dc5c-4b9f-931c-d15ce5347760.png)

**Comment by etrigan63** [comment]
Done.

**Comment by etrigan63** [comment]
Fixed and updated.
[image: photo]
Carlos Echenique
Photographer at  CE Photographic
P  305.219.2433  <305.219.2433>
E  ***@***.***  ***@***.***>
W  cephotographic.com  <http://cephotographic.com>
<http://instagram.com/cephotographic> <http://facebook.com/cephotos>
<http://www.flickr.com/photos/echenique>

"Behind every great man is a woman rolling her eyes." - Jim Carrey.
Create your own email signature
<https://www.wisestamp.com/create-own-email-signature/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>
